language: bash
services: docker

env:
  - PROJECT_PHP_VERSION=56
  - PROJECT_PHP_VERSION=70
  - PROJECT_PHP_VERSION=71

before_script:
  - env | sort
  - if [[ "PROJECT_PHP_VERSION" == "71" ]]; then docker pull php:7.1-fpm; fi;
  - if [[ "PROJECT_PHP_VERSION" == "70" ]]; then docker pull php:7.0-fpm; fi;
  - if [[ "PROJECT_PHP_VERSION" == "56" ]]; then docker pull php:5.6-fpm; fi;

script:
  - ./docker.sh build "${PROJECT_PHP_VERSION}" true
  - ./docker.sh build "${PROJECT_PHP_VERSION}" false
