language: bash
services: docker

env:
  - PROJECT_COMMAND=build
  - PROJECT_COMMAND=build-coverage
  - PROJECT_COMMAND=build-56

before_script:
  - env | sort
  - if [[ "$PROJECT_COMMAND" != "build-56" ]]; then docker pull php:7.0-fpm; fi;
  - if [[ "$PROJECT_COMMAND" == "build-56" ]]; then docker pull php:5.6-fpm; fi;

script:
  - ./docker.sh "${PROJECT_COMMAND}"
