data:
  image: busybox
  volumes:
    - .:/var/www

php:
  image: "${IMAGE_VERSION}"
  entrypoint: "/bin/bash"
  command: "/entrypoint.sh"
  links:
    - mysql
  volumes_from:
    - data
  environment:
    SYMFONY_ENV: test
    ENABLED_XDEBUG: "${ENABLED_XDEBUG}"

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
    MYSQL_DATABASE: ${PROJECT_NAME}
