data:
  image: busybox
  volumes:
    - .:/var/www

php:
  image: "${IMAGE_VERSION}"
  entrypoint: "/bin/bash"
  command: "/entrypoint.sh"
  links:
    - mysql
  volumes_from:
    - data
  environment:
    PROJECT_XDEBUG_ENABLED: ${PROJECT_XDEBUG_ENABLED}
    PROJECT_USER_ID: ${PROJECT_USER_ID}
    PROJECT_GROUP_ID: ${PROJECT_GROUP_ID}

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
    MYSQL_DATABASE: ${PROJECT_NAME}
